### ISSUE TITLE
dl.bintray.com/kevinlee/maven returning 403 Forbidden response

### ISSUE THREAD

**Issue by jrdmcgr** [Kevin-Lee/one-jar-boot#5]
http://dl.bintray.com/kevinlee/maven is a giving 403 Forbidden response.

Here is the full build error I'm seeing.

```
[ERROR] Failed to execute goal on project transitclockCore: Could not resolve dependencies for project TheTransitClock:transitclockCore:jar:2.0.0-SNAPSHOT: Failed to collect dependencies at com.simontuffs:one-jar-boot:jar:0.97.3: Failed to read artifact descriptor for com.simontuffs:one-jar-boot:jar:0.97.3: Could not transfer artifact com.simontuffs:one-jar-boot:pom:0.97.3 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [bintray-kevinlee-maven (http://dl.bintray.com/kevinlee/maven, default, releases)] -> [Help 1]
```

**Comment by jrdmcgr** [comment]
I see that the bintray.com service has been "sunset". The message on their site says: "Thanks for supporting Bintray! This service has now been sunset, and to assist with migration to the JFrog Platform, paid accounts can login until July 4th."

Do you know of another way to support this dependency in my project?

**Comment by er1c** [comment]
@Kevin-Lee can you publish this to sonatype/maven? Or, alternatively to GitHub artifacts?

**Comment by kevin-lee** [comment]
@jrdmcgr Oops! Sorry I just saw ticket. I'll publish it to the Maven Central.
@er1c Sure, I will.

**Comment by kevin-lee** [comment]
I will do it this weekend.

**Comment by er1c** [comment]
@Kevin-Lee thanks boss!

**Comment by kevin-lee** [comment]
@jrdmcgr @er1c
Oh! NO!!! I forgot to mention the ticket number in my commit. 😢
It's done! (#15) I've also updated the README. Please let me know if you find any issue.

**Comment by kevin-lee** [comment]
I'm sorry but could you do me a favor? I found a branch that I was working on to fix [this issue](https://github.com/aws/aws-sdk-java/issues/185). I'm not sure if the latest `one-jar-boot` release fixes it since it was about six years ago when I last released it. So if you find it's still the problem, could you please let me know?
